name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      PYTHONIOENCODING: utf-8
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: "false"

    - name: Install main
      shell: bash
      run: |
        make install

    - name: Lint
      shell: bash
      run: |
        make lint

    - name: Mypy
      shell: bash
      run: |
        make mypy

    - name: Test
      shell: bash
      run: |
        make test

    - name: Install from dist
      shell: bash
      run: |
        make build
        pip install dist/*.whl
